#!/bin/bash
#
# Set up a simulated domain using UML
#

# Set usage output
USAGE="[-ht] <config-file>"
LONGUSAGE="\t-h\tPrint this help message
\t-t\tTest mode.  Doesn't start any processes, but generates config
\t<config-file>\tConfig file to run"

function UMLcleanup() {
	# Stop our switches
	killall uml_switch
	# Clean up tap
	if [ -n "${TAPNAME}" ]; then
		tunctl -d ${TAPNAME}
	fi
}

source @PREFIX@/uml-functions.sh

LINUX="linux"
TESTDIR="."
MEM="64M"
ROOTFS="root_fs"
SWAPFS="swap_fs"
HOST_DOMAIN=$(dnsdomainname)

# Parse arguments
while getopts ":ht" option; do
	case ${option} in
		t ) TESTMODE="yes";;
		h ) usage;;
		\? ) usage "Invalid argument ${OPTARG}";;
		* ) usage "Invalid argument ${option}";;
	esac
done

if [ "${OPTIND}" != "0" ]; then
	shift $((OPTIND-1))
fi

if [ -z "$1" ]; then
	usage "Error: no conf file"
fi

CONFFILE=$1
TESTNAME=`basename ${CONFFILE} .conf`
if [ -z $TESTNAME ]; then
	die "Error: conf file name \"${CONFFILE}\" invalid.  Must be in the form /path/to/file.conf"
fi

TESTDIR=`dirname ${CONFFILE}`;
if [ -z "${TESTDIR}" ]; then
	die "Error: conf file name \"${CONFFILE}\" invalid.  Must be in the form /path/to/file.conf"
fi

if [ "${TESTDIR}" == "." ]; then
	TESTDIR=$(pwd)
fi

if [ -a ${TESTDIR}/${LINUX} ]; then
	echo "Running ${TESTDIR}/${LINUX}"
elif [ -z ${TESTMODE} ]; then
	die "No ${TESTDIR}/${LINUX}"
fi

if [ -a ${TESTDIR}/${ROOTFS} ]; then
	echo "root_fs: ${TESTDIR}/${ROOTFS}"
elif [ -z ${TESTMODE} ]; then
	die "No ${TESTDIR}/${ROOTFS}"
fi

if [ -a ${TESTDIR}/${SWAPFS} ]; then
	echo "root_fs: ${TESTDIR}/${SWAPFS}"
elif [ -z ${TESTMODE} ]; then
	die "No ${TESTDIR}/${SWAPFS}"
fi

source ${CONFFILE}

# Set up the box directories
for MACHINE in ${MACHINES}; do
	if [ ! -d ${TESTDIR}/${MACHINE}/conf.d ]; then
		if [ ! -d ${TESTDIR}/../base ]; then
			die "Cannot create machine directory for ${MACHINE}: no base dir"
		fi

		mkdir -p ${TESTDIR}/${MACHINE}/conf.d || die "Couldn't create ${TESTDIR}/${MACHINE}/conf.d"
		cd ${TESTDIR}/${MACHINE}/conf.d 
		for i in $(/bin/ls ${TESTDIR}/../base/conf.d); do
			cp ${TESTDIR}/../base/conf.d/$i . || die "Couldn't copy $i"
		done
		cd ${TESTDIR}
	fi
done

# Set up the runtime state
RUNDIR=${TESTDIR}/run
if [ "${PERSISTENT_ROOTFS:=no}" != "yes" ]; then
	echo "Running non-persistent"
	rm -rf ${RUNDIR}
else
	echo "Running persistent"
fi

mkdir -p ${RUNDIR}

# Configure host network access
if [ -n "${HOST_NETWORK}" ]; then
	HOST_NET_IP4=NET_IP4_${HOST_NETWORK}
	if [ -z "${!HOST_NET_IP4}" ]; then
		die "Host is on network ${HOST_NETWORK} but it's not configured"
	fi
	BCAST_IP4=NET_IP4_BCAST_${HOST_NETWORK}
	if [ -z "${!BCAST_IP4}" ]; then
		die "Host is on network ${HOST_NETWORK} but it's not configured"
	fi
	MASKLEN_IP4=NET_IP4_MASKLEN_${HOST_NETWORK}
	if [ -z "${!MASKLEN_IP4}" ]; then
		die "Host is on network ${HOST_NETWORK} but it's not configured"
	fi
	generate_ip4 ${!HOST_NET_IP4} ${DEC_HOST}

	TAPNAME="uml-tap${HOST_NETWORK}"

	if [ -z ${TESTMODE} ]; then
		tunctl -u ${USER} -t ${TAPNAME}
		sudo ip link set ${TAPNAME} up
		sudo ip addr add ${GENERATE_IP4_RETURN}/${!MASKLEN_IP4} broadcast ${!BCAST_IP4} dev ${TAPNAME}

		NET_IP6=NET_IP6_${HOST_NETWORK}
		MASKLEN_IP6=NET_IP6_MASKLEN_${HOST_NETWORK}
		if [ -n "${!NET_IP6}" ] && [ -n "${!MASKLEN_IP6}" ]; then
			sudo ip addr add ${!NET_IP6}::${HEX_HOST}/${!MASKLEN_IP6} dev ${TAPNAME}
		fi
	fi
fi

# Verify network config and start switch daemons for networks
for NET in ${NETWORKS}; do
	TMP=NET_IP4_${NET}
	if [ -z ${!TMP} ]; then
		die "${TMP} not configured"
	fi
	TMP=NET_IP4_MASKLEN_${NET}
	if [ -z ${!TMP} ]; then
		die "${TMP} not configured"
	fi
	TMP=NET_IP4_BCAST_${NET}
	if [ -z ${!TMP} ]; then
		die "${TMP} not configured"
	fi
	TMP=NET_IP6_${NET}
	if [ -n ${!TMP} ]; then
		# v6 is optional, but both are necessary.
		TMP=NET_IP6_MASKLEN_${NET}
		if [ -z ${!TMP} ]; then
			die "${TMP} not configured"
		fi
	fi

	if [ -z ${TESTMODE} ]; then
		if [ "z${HOST_NETWORK}" == "z${NET}" ]; then
			uml_switch -unix ${RUNDIR}/network${NET} -tap ${TAPNAME} &
		else
			uml_switch -unix ${RUNDIR}/network${NET} &
		fi
	fi
done

# Create config for each box
for MACHINE in ${MACHINES}; do
	echo "Configuring ${MACHINE}"
	HEX=HEX_${MACHINE}
	if [ -z "${!HEX}" ]; then
		die "No ${HEX} configured"
	fi
	DEC=DEC_${MACHINE}
	if [ -z "${!DEC}" ]; then
		die "No ${DEC} configured"
	fi

	if [ ! -d ${TESTDIR}/${MACHINE} ]; then
		die "No config directory for ${MACHINE}"
	fi
	CONFDIR="${TESTDIR}/${MACHINE}/conf.d"
	if [ ! -d ${CONFDIR} ]; then
		die "No conf.d directory for ${MACHINE}"
	fi

	# Create local.start
	echo "local.start"
	echo -e "# /etc/conf.d/local.start" > ${CONFDIR}/local.start
	echo -e "# GENERATED -- DO NOT EDIT" >> ${CONFDIR}/local.start
	echo -e "echo 'core.%e-%p' > /proc/sys/kernel/core_pattern" >> ${CONFDIR}/local.start
	echo -e "env-update" >> ${CONFDIR}/local.start
	LOOP=LOOP_IP4_${MACHINE}
	if [ -n "${!LOOP}" ]; then
		echo -e "ip addr add ${!LOOP} dev lo" >> ${CONFDIR}/local.start
	else
		LOOP="192.${!DEC}.${!DEC}.${!DEC}/32"
		echo -e "ip addr add ${LOOP} dev lo" >> ${CONFDIR}/local.start
	fi
	LOOP=LOOP_IP6_${MACHINE}
	if [ -n "${!LOOP}" ]; then
		echo -e "ip addr add ${!LOOP} dev lo" >> ${CONFDIR}/local.start
	else
		LOOP="fec0:${!HEX}${!HEX}:${!HEX}${!HEX}:${!HEX}${!HEX}::${!HEX}/128"
		echo -e "ip addr add ${LOOP} dev lo" >> ${CONFDIR}/local.start
	fi

	# Create hostname
	echo "hostname"
	echo -e "# /etc/conf.d/hostname" > ${CONFDIR}/hostname
	echo -e "# GENERATED -- DO NOT EDIT" >> ${CONFDIR}/hostname
	echo -e "HOSTNAME='${MACHINE}'" >> ${CONFDIR}/hostname

	# Create domainname
	echo "domainname"
	echo -e "# /etc/conf.d/domainname" > ${CONFDIR}/domainname
	echo -e "# GENERATED -- DO NOT EDIT" >> ${CONFDIR}/domainname
	echo -e "OVERRIDE=1" >> ${CONFDIR}/domainname
	echo -e "DNSDOMAIN=\"${HOST_DOMAIN}\"" >> ${CONFDIR}/domainname
	echo -e "NISDOMAIN=\"nis.${HOST_DOMAIN}\"" >> ${CONFDIR}/domainname

	# Create hosts
	echo "hosts"
	echo -e "# /etc/conf.d/hosts" > ${CONFDIR}/hosts
	echo -e "# GENERATED -- DO NOT EDIT" >> ${CONFDIR}/hosts
	echo -e "127.0.0.1\tlocalhost" >> ${CONFDIR}/hosts
	for DNS_MCH in ${MACHINES}; do
		DNS_IP=DNS_IP_${DNS_MCH}
		if [ -n "${!DNS_IP}" ]; then
			DNS=${!DNS_IP}
		elif [ -n "${HOST_NETWORK}" ]; then
			TMP=DEC_${DNS_MCH}
			generate_ip4 ${!HOST_NET_IP4} ${!TMP}
			DNS=${GENERATE_IP4_RETURN}
		else
			die "You must either set ${DNS_IP} or HOST_NETWORK"
		fi
		echo -e "${DNS}\t${DNS_MCH}.${HOST_DOMAIN} ${DNS_MCH}" >> ${CONFDIR}/hosts
	done
	if [ -n "${HOST_IP4}" ]; then
		# Add name of host
		echo -e "${HOST_IP4}\t$(hostname).$(dnsdomainname) $(hostname)" >> ${CONFDIR}/hosts
	fi

	# Create net
	echo "net"
	echo -e "# /etc/conf.d/net" > ${CONFDIR}/net
	echo -e "# GENERATED -- DO NOT EDIT" >> ${CONFDIR}/net
	echo -e "modules=( 'iproute2' )" >> ${CONFDIR}/net
	NETS=NETWORKS_${MACHINE}
	if [ -z "${!NETS}" ]; then
		die "No ${NETS}"
	fi
	for NET in ${!NETS}; do
		# Verify network is configured
		TMP=NET_IP4_${NET}
		if [ -z "${!TMP}" ]; then
			die "Network ${NET} not configured"
		fi

		NETDEV=NETDEV_${MACHINE}_${NET}
		if [ -z "${!NETDEV}" ]; then
			die "No ${NETDEV}"
		fi

		NETIP4=NETIP4_${MACHINE}_${NET}
		if [ -n "${!NETIP4}" ]; then
			TMP=${!NETIP4}
		else
			NETIP4=NET_IP4_${NET}
			MASKLEN=NET_IP4_MASKLEN_${NET}
			generate_ip4 ${!NETIP4} ${!DEC}
			TMP="${GENERATE_IP4_RETURN}/${!MASKLEN}"
		fi
		echo -e "config_${!NETDEV}=(" >> ${CONFDIR}/net
		echo -e "\t\"${TMP}\"" >> ${CONFDIR}/net

		NETIP6=NETIP6_${MACHINE}_${NET}
		if [ -n "${!NETIP6}" ]; then
			TMP=${!NETIP6}
		else
			NETIP6=NET_IP6_${NET}
			MASKLEN=NET_IP6_MASKLEN_${NET}
			TMP="${!NETIP6}::${!HEX}/${!MASKLEN}"
		fi
		echo -e "\t\"${TMP}\"" >> ${CONFDIR}/net
		echo -e ")" >> ${CONFDIR}/net
	done

done

if [ -n "${XTERM}" ]; then
	XTERMLINE="xterm=${XTERM}"
fi

# Start up each UML box
for MACHINE in ${MACHINES}; do
	ETHLINE=""

	TMAC=HEX_${MACHINE}
	if [ -z "${!TMAC}" ]; then
		die "No HEX octet configured for ${MACHINE}"
	fi

	NETS=NETWORKS_${MACHINE}
	if [ -z "${!NETS}" ]; then
		die "No ${NETS}"
	fi

	# Build network list for each network
	for NET in ${!NETS}; do
		NETMACBYTE=$(printf "%02d" ${NET})
		NETDEV=NETDEV_${MACHINE}_${NET}
		ETHLINE="${ETHLINE} ${!NETDEV}=daemon,FE:FD:67:45:${NETMACBYTE}:${!TMAC},unix,${RUNDIR}/network${NET}"
	done

	if [ -z "${ETHLINE}" ]; then
		die "No ethernets configured for ${MACHINE}"
	fi

	# Mount /stuff, /share, and /home
	#echo sudo mount -o bind /stuff ${TESTDIR}/${MACHINE}/stuff
	#echo sudo mount -o bind /share ${TESTDIR}/${MACHINE}/share
	#echo sudo mount -o bind /home ${TESTDIR}/${MACHINE}/home

	if [ -z ${TESTMODE} ]; then
		echo "Starting ${MACHINE}"
		screen -DmS uml-${MACHINE} ${TESTDIR}/${LINUX} umid=${MACHINE} \
			ubd0=${RUNDIR}/${ROOTFS}.${MACHINE}.cow,${TESTDIR}/${ROOTFS} \
 			ubd1=${RUNDIR}/${SWAPFS}.${MACHINE}.cow,${TESTDIR}/${SWAPFS} \
			mem=${MEM} ${ETHLINE} hostfs=${TESTDIR}/${MACHINE}/conf.d \
			${XTERMLINE} &
	else
		echo "Test mode; not starting ${MACHINE}"
	fi
done

if [ -n "${TESTMODE}" ]; then
	# Done
	exit
fi

sleep 1
SCREENPIDS=$(screen -ls | grep uml | awk -F . '{print $1}')
if [ -n "${SCREENPIDS}" ]; then
	wait ${SCREENPIDS}
fi

# clean up after ourselves
UMLcleanup
