#!/bin/bash
#
# Start/stop the mounts for building UML images
#

source @PREFIX@/uml-functions.sh

if [ -z "$1" ]; then
	BUILDDIR="`pwd`"
else
	BUILDDIR="$1"
fi

# Stop if it was started
uml-build-stop

# Mount /proc, /usr/portage, /home/portage
sudo mount -o bind /proc ${BUILDDIR}/proc || die "Mount of /proc failed"
sudo mount -o bind /usr/portage ${BUILDDIR}/usr/portage || die "Mount of /usr/portage failed"
sudo mount -o bind /home/portage ${BUILDDIR}/home/portage || die "Mount of /home/portage failed"
sudo mount -o bind ${BUILDDIR}/../kernel ${BUILDDIR}/usr/src || die "Mount of /usr/src failed"
sudo cp /etc/resolv.conf ${BUILDDIR}/etc || die "Couldn't cp /etc/resolv.conf"

# Now, start screen and chroot
cd ${BUILDDIR}
screen -S uml-build -t uml-build sudo -H schedtool -D -e chroot ${BUILDDIR} /bin/bash -l
