#!/bin/bash
#
# Start/stop the mounts for building UML images
#

source @PREFIX@/uml-functions.sh

if [ -z "$1" ]; then
	BUILDDIR="`pwd`"
else
	BUILDDIR="$1"
fi

source ${BUILDDIR}/etc/make.globals
source ${BUILDDIR}/etc/make.conf

if [ -z "${PORTDIR}" ]; then
	die "No PORTDIR.  Are /etc/make.globals and /etc/make.conf broken?"
fi
if [ -z "${PORTAGE_TMPDIR}" ]; then
	die "No PORTAGE_TMPDIR.  Are /etc/make.globals and /etc/make.conf broken?"
fi
if [ -z "${DISTDIR}" ]; then
	die "No DISTDIR.  Are /etc/make.globals and /etc/make.conf broken?"
fi

UMOUNT_DIRS="${BUILDDIR}/proc ${BUILDDIR}${PORTDIR} \
	${BUILDDIR}${PORTAGE_TMPDIR} ${BUILDDIR}${DISTDIR} \
	${BUILDDIR}/usr/src"

for dir in ${PORTDIR_OVERLAY}; do
	UMOUNT_DIRS="${UMOUNT_DIRS} ${BUILDDIR}${dir}"
done
# unmount stuff that we mounted
sudo umount ${UMOUNT_DIRS} || die "umounts failed"
