#!/bin/bash
#
# Start/stop the mounts for building UML images
#

source @PREFIX@/uml-functions.sh

CURDIR="$(pwd)"
BUILDDIR="${CURDIR}/build"
MNTDIR="${CURDIR}/mnt"
IMG="${CURDIR}/root_fs"

if [ ! -d ${BUILDDIR} ]; then
	die "No ${BUILDDIR}"
fi
if [ ! -d ${MNTDIR} ]; then
	die "No ${MNTDIR}"
fi
if [ ! -f ${IMG} ]; then
	die "No ${IMG}"
fi

# Stop uml-build if it was started
cd ${BUILDDIR}
uml-build-stop > /dev/null
cd ${CURDIR}

# Mount image
sudo mount -o loop ${IMG} ${MNTDIR} || die "Couldn't mount ${IMG}"
sudo rsync -av --delete --progress ${BUILDDIR}/ ${MNTDIR} || die "rsync failed"
sudo umount ${MNTDIR} || die "Couldn't unmount ${MNTDIR}"
